language: c

notifications:
  email: false

branches:
  only:
    - master
    - release

sudo: required

matrix:
  include:
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-6

install:
  - bash .travis_install.bash

script:
  - make
